site_name: agex
site_description: Library-friendly agents for Python
site_url: https://ashenfad.github.io/agex

repo_name: ashenfad/agex
repo_url: https://github.com/ashenfad/agex


theme:
  name: material
  favicon: assets/code-braces.svg
  logo: assets/code-braces.svg
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - toc.integrate
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotate

nav:
  - Home: index.md
  - Quick Start: quick-start.md
  - Concepts:
    - Overview: concepts/overview.md
    - The Big Picture: concepts/big-picture.md
    - A Note on MCP: concepts/agex-and-mcp.md
    - Security: concepts/security.md
    - Nearly Python: concepts/nearly-python.md
  - Examples:
    - Overview: examples/overview.md
    - Agex 101 (notebook): examples/agex101.ipynb
    - Routy (notebook): examples/routy.ipynb
    - Mathy: examples/mathy.md
    - Funcy: examples/funcy.md
    - DB (SQLite): examples/db.md
    - Hierarchical: examples/hierarchical.md
    - Evaluator–Optimizer: examples/evaluator_optimizer.md
    - Dogfood (agents creating agents): examples/dogfood.md
  - API Reference:
    - Overview: api/overview.md
    - Agent: api/agent.md
    - Registration: api/registration.md
    - Task: api/task.md
    - State: api/state.md
    - Events: api/events.md
    - Errors: api/errors.md
    - View: api/view.md
    - Helpers: api/helpers.md
    - Benchmarking: api/benchmarking.md
  - Roadmap:
    - Overview: roadmap/overview.md
    - Contextual Primers: roadmap/primers.md
    - System Token Counting: roadmap/token_counting.md
    - MIME Bundles for Events: roadmap/mime_bundles.md
    - Local Registries: roadmap/local_registries.md
    - Faded Memory: roadmap/faded_memory.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocs-jupyter:
      execute: false
      allow_errors: false
      include_source: true
      ignore_h1_titles: true
      include_requirejs: false
      kernel_name: python3

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ashenfad/agex
  version:
    provider: mike
  authors:
    - slug: ashenfad
      name: ashenfad
      link: https://github.com/ashenfad

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/plotly.js@2.35.2/dist/plotly.min.js
  - assets/plotly-init.js
