site_name: agex
site_description: Library-friendly agents for Python
site_url: https://ashenfad.github.io/agex

repo_name: ashenfad/agex
repo_url: https://github.com/ashenfad/agex

theme:
  name: material
  favicon: assets/code-braces.svg
  logo: assets/code-braces.svg
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotate

nav:
  - Home: index.md
  - Quick Start: quick-start.md
  - The Big Picture: big-picture.md
  - Demos:
    - Agex 101: demos/agex101.ipynb
  - API Reference:
    - Overview: api/overview.md
    - Agent: api/agent.md
    - Registration: api/registration.md
    - Task: api/task.md
    - State: api/state.md
    - Events: api/events.md
    - Errors: api/errors.md
    - View: api/view.md
  - Examples:
    - Overview: examples/overview.md
  - Security: security.md
  - Development:
    - Nearly Python: nearly-python.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocs-jupyter:
      execute: false
      allow_errors: false
      include_source: true
      ignore_h1_titles: true
      include_requirejs: true
      kernel_name: python3
      theme: dark

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ashenfad/agex
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/plotly.js@2.35.2/dist/plotly.min.js
