[project]
name = "tic"
version = "0.1.0"
description = "A tic-tac-toe game."
requires-python = ">=3.12"
dependencies = []

[project.optional-dependencies]
dev = [
    "ruff",
    "pre-commit",
]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]

[tool.uv]
dev-dependencies = [
    "ruff",
    "pre-commit",
] 