name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[test,dev]"

    - name: Lint with ruff
      run: |
        ruff check .
        ruff format --check .

    - name: Run tests
      run: |
        pytest -v

  test-examples:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[examples,test]"

    - name: Test examples (dry run)
      run: |
        # Test that examples import and basic structure is valid
        python -c "import examples.mathy; print('mathy.py imports successfully')"
        python -c "import examples.funcy; print('funcy.py imports successfully')"
        python -c "import examples.viz; print('viz.py imports successfully')"
        python -c "import examples.db; print('db.py imports successfully')"
        python -c "import examples.hierarchical; print('hierarchical.py imports successfully')"
        python -c "import examples.evaluator_optimizer; print('evaluator_optimizer.py imports successfully')"
        python -c "import examples.dogfood; print('dogfood.py imports successfully')"
